version: '3.1'

services:
  builder:
    restart: "no"
    build: ./
    container_name: montpedigital_builder
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/app
    entrypoint: 
      - yarn
      - build   